"com.luqiao.tunneltone", #隧e通
"com.tencent.letsgo", #元梦之星
"com.tencent.mm", #微信
"com.xingin.xhs", #小红书
"com.sunboxsoft.charge.institute", #中油好客e站
"com.xiaomi.youpin", #小米有品
"com.mi.car.mobile", #小米汽车
"com.xiaomi.hm.health", #Zepp Life
"com.mi.health", #小米运动健康
"com.tencent.lolm", #英雄联盟手游
"org.localsend.localsend_app", #LocalSend
"com.bankcomm.maidanba", #买单吧
"com.spdbccc.app", #浦大喜奔
"cn.gov.tax.its", #个人所得税
"com.homelink.android", #链家
"com.wudaokou.hippo", #盒马
"com.miui.weather2", #小米天气
"com.lucky.luckyclient", #瑞幸咖啡
"com.umetrip.android.msky.app", #航旅纵横
"com.xiaomi.smarthome", #米家
"com.generalcomp.batian", #霸天安云
"global.longbridge.app.android", #长桥
"com.quark.browser", #夸克
"com.starbucks.cn", #星巴克
"com.chinamworld.bocmbci", #中国银行
"cmb.pb", #招商银行
"com.cmbchina.ccd.pluto.cmbActivity", #掌上生活
"com.netease.mobimail", #网易邮箱
"com.taobao.taobao", #淘宝
"com.taobao.trip", #飞猪
"me.ele", #饿了么
"com.dianping.v1", #大众点评
"com.eg.android.AlipayGphone", #支付宝
"com.cainiao.wireless", #菜鸟
"com.alibaba.android.rimet", #钉钉
"com.tencent.mobileqq", #QQ
"com.tencent.qqmusic", #QQ音乐
"com.tencent.mm", #微信
"com.tencent.wework", #企业微信
"com.tencent.weread", #微信读书
"com.tencent.tmgp.sgame", #王者荣耀
"com.tencent.karaoke", #全民K歌
"com.sankuai.meituan", #美团
"com.taobao.idlefish", #闲鱼
"com.MobileTicket", #铁路12306
"battymole.trainticket", #航班管家
"com.xunmeng.pinduoduo", #拼多多
"com.jingdong.app.mall", #京东
"ctrip.android.view", #携程
"com.sina.weibo", #微博
"com.ss.android.ugc.aweme", #抖音
"com.tencent.android.qqdownloader", #应用宝
"com.youku.phone", #优酷
"com.qiyi.video", #爱奇艺
"com.tencent.qqlive", #腾讯视频
"com.baidu.BaiduMap", #百度地图
"com.autonavi.minimap", #高德地图
"com.sdu.didi.psnger", #滴滴出行
"com.netease.cloudmusic", #网易云音乐
"com.ximalaya.ting.android", #喜马拉雅
"com.alicloud.databox", #阿里云盘
"com.jd.jrapp", #京东金融
"com.umpay.qingdaonfc", #琴岛通
"cn.gov.pbc.dcep", #数字人民币
"com.qdznjt.qdtc.jtjt", #青岛停车
"com.cnspeedtest.globalspeed", #全球网测
"cn.futu.trader", #富途牛牛
"com.unionpay", #云闪付
"com.xiaomi.router", #小米路由器
"com.jin10", #金十数据
"com.tencent.wetype", #微信输入法
"com.thestore.main", #1号会员店
"com.huawei.smarthome", #智慧生活
"com.tmri.app.main", #交管12123
"com.anjuke.android.app", #安居客
"com.lianjia.beike", #贝壳找房
"com.server.auditor.ssh.client", #Termius
"com.eastmoney.android.choice", #Choice数据
"com.coloros.soundrecorder", #录音机
"com.redteamobile.roaming", #
"com.coloros.backuprestore", #
"com.heytap.music", #
"com.coloros.calendar", #
"cn.wps.moffice.lite", #
"com.coloros.calculator", #
"andes.oplus.documentsreader", #
"com.oneplus.member", #
"com.netease.dwrg.nearme.gamecenter", #
"com.ifreegroup.moesim", #
"com.xiaomi.mico", #
"com.coloros.favorite", #
"com.qq.qcloud", #
"com.tencent.map", #
"com.coloros.filemanager", #
"com.coloros.alarmclock", #
"com.coloros.weather2", #
"com.heytap.health", #
"com.coloros.compass2", #
"com.sdjictec.qdmetro", #
"tv.danmaku.bili", #
"com.oneplus.bbs", #
"com.unionpay.tsmservice", #
"com.coloros.familyguard", #
"com.ct.client", #
"com.thestore.main", #
"cn.cyberIdentity.certification", #
"com.oplus.consumerIRApp", #
"com.coloros.shortcuts", #
"com.coloros.translate", #
"com.heytap.book", #
"cn.caocaokeji.user", #
"com.finshell.wallet", #
"com.oplus.play", #
"com.oppo.store", #
"com.sohu.inputmethod.sogouoem", #
"com.wolai.flutter_app", #
"com.ai.obc.cbn.app", #
"com.nearme.gamecenter", #
"com.oplus.melody", #
"com.heytap.themestore", #
"com.coloros.note", #
"com.sf.activity", #
"com.heytap.yoli", #
"com.oneplus.brickmode", #
"com.clover.daysmatter", #
"com.oplus.games", #
"com.xueqiu.android", #
"cn.com.hkgt.gasapp", #
"com.mfcloudcalculate.networkdisk", #
"com.rpms.uaandroid" #